* Introduction
** The goal of this course is to learn how to organise code. By "organise", we mean how to split a long script or piece of code into functions and classes; how to collect those functions and classes into different files; and how to adopt libraries of reusable functions.
** The principle motivation is making your code easier to understand and change.
** Secondary motivation is that we're promoting reuse; you'll see that identical code in many places in a script can be extracted into a single function, and that a file of useful functions can be shared between projects.
** Finally by introducing the idea of using other libraries, we aim to reduce the amount of code you have to write and thus the time spent maintaining and fixing it.
* Designing Organised Code
** We need to know what we're aiming for.
** Duplication is bad, because when we have to change something we're going to have to change it in multiple places, and we might miss some.
** But we don't just arbitrarily look for duplicate code and break it up.
*** Cohesion - does this function, or class, do a single thing? Are its parts (subroutines/methods) clearly related? Is it the _only_ place I have to look to see how this thing is done? Aim for designs the increase cohesion.
*** Coupling - does this function make changes to an unrelated part of the program? Does it some distant structure to be set up, or some other calls to be made in exactly the right order, before it can be used? Aim for designs that reduce coupling.
**** Types of coupling from Code Complete 2:
***** simple data parameters (this module calls a function from that module, passing int, string etc)
***** simple object coupling (this module creates an instance of that object)
***** object-parameter coupling (this module needs that module to pass it an instance of this third object)
***** control flag coupling
***** temporal coupling via global data
***** relying on behaviour that isn't explicit in the contract (i.e. documentation and tests), whether in behaviour or in data
*** Value - will I get anything from separating this out - easier to understand, easier to change, easier to reuse? Does that value outweigh the risk of breaking things when I make changes? (Hint; version control and tests!)
*** Non-consideration: performance. It's almost always more valuable to have a readable function than to shave a few nanoseconds of function call off your runtime.
** We need to introduce the concept of "smells" at this point: there's no hard limit on the length of a function, or amount of coupling, etc., just a sense that things could be better
* Organising Existing Code
** We'll explain how to do it the long-winded way, but look for a code editor or IDE that can do it automatically.
** Need examples here!
** Case One: break long script into separate procedures/routines
*** Identify the distinct high-level "steps" in the script, perhaps draw a flowchart
*** Pick one of these "steps". Identify the data it consumes (i.e. what flows in) and the results it produces (i.e. what flows out), and define a procedure/function that has the same inputs and outputs. Note that if you use "global variables" in the script, you should make them parameters to the procedure where possible.
*** if the inputs or (especially) outputs are complex, consider defining structures or classes to keep related parts together.
*** copy the procedure from the script into the definition, and fix up any changes needed e.g. making variable names match the parameters in the procedure.
*** remove the statements from the script and replace with a call to the new procedure.
*** test!
** Case Two: replacing duplicate code with procedures
*** Identify the duplicate code, and its purpose
*** Is it really duplicate? Are there differences in how values are handled, or in particular operations?
*** Antipattern: it's generally not a good idea to deduplicate two "almost-the-same" code blocks into one procedure with a switch telling it to do version 1 or 2, because that's just as hard to understand.
*** Is there code that _could_ be duplicate, but that coincidentally uses e.g. different filesystem routines or the same operations in different orders?
*** Follow the steps in "case one" to replace one of the instances.
*** Now replace the second (and third...) invocations.
* Using multiple files
** You've probably now broken a big script into...another big script that has lots of functions or procedures in.
** Identify clusters of related functions and separate them into files. You have less code to read when you want to find a specific thing to change, and you can take these files and use them in other projects \o/
** Use your language's import/include/using mechanism to get them back again (very different examples: Python, C++)
** Now you know how to do this, you can use other people's code and shrink your scripts even further
*** describe package repositories: example of pypi, CRAN
*** make sure to control what version of the package you get
*** fetching and using somebody's package
* Functional programming
** While many languages call any sequence of instructions a "function", there's a mathematical meaning
** A function transforms its inputs into its output without relying on external state or making other changes
** Benefits: much easier to understand, because all of the behaviour is described by the code in front of you. Easier to change or even replace without worrying over surprising consequences.
* Object-oriented programming
** Related procedures that all act on the same data can be collected into a "class" which describes a prototype of those data, and the ways the procedures work on it.
** Benefits: data use across procedures can be made consistent; any validation or other interaction between the procedures can be encapsulated in the class; data can be restricted to those procedures so no other changes happen.

